/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nastavnikclient;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import nastavnikcommon.Angazovanje;
import nastavnikcommon.Nastavnik;
import nastavnikcommon.Predmet;

/**
 *
 * @author Ljubomir
 */
public class MainForm extends javax.swing.JFrame {

    Controller controller;
    Nastavnik nastavnik;
    AngazovanjaTableModel model;

    /**
     * Creates new form MainForm
     */
    public MainForm(Controller c, Nastavnik nastavnik) throws Exception {
        initComponents();
        this.controller = c;
        this.nastavnik = nastavnik;
        System.out.println("OVAKO DOBIJAM NASTAVNIKA IZ BASE");
        System.out.println(nastavnik);
        fillPredmetiCmb();
        model = new AngazovanjaTableModel();
        tblAngazovanja.setModel(model);
        getPredmetCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPredmeti = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngazovanja = new javax.swing.JTable();
        btnNovoAngazovanje = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnObrisiAng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbPredmeti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPredmeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPredmetiActionPerformed(evt);
            }
        });

        tblAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAngazovanja);

        btnNovoAngazovanje.setText("Dodaj novo angazovanje");
        btnNovoAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAngazovanjeActionPerformed(evt);
            }
        });

        btnSave.setText("Sacuvaj promene");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnObrisiAng.setText("Obrisi agnazovanje");
        btnObrisiAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiAngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNovoAngazovanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(cmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnObrisiAng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(cmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnObrisiAng)
                .addGap(18, 18, 18)
                .addComponent(btnNovoAngazovanje)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPredmetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPredmetiActionPerformed
        Predmet predmet = (Predmet) cmbPredmeti.getSelectedItem();
        try {
            List<Angazovanje> angazovanje = controller.getAllAngazovanjaByPredmet(predmet);
            model.setAngazovanja(angazovanje);
            model.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_cmbPredmetiActionPerformed

    private void btnNovoAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAngazovanjeActionPerformed
        Angazovanje a = new Angazovanje();
        a.setNastavnik(nastavnik);
        System.out.println("LOGOVAN SRMAD");
        System.out.println(nastavnik);
        Predmet p = new Predmet();
        a.setPredmet(p);
        a.setTipAngazovanja("");
        model.getAngazovanja().add(a);
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnNovoAngazovanjeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            List<Angazovanje> ang = model.getAngazovanja().stream().filter(a -> a.getNastavnik().getIme().equals(nastavnik.getIme())).collect(Collectors.toList());
            
            controller.saveAngazovanje(ang);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnObrisiAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiAngActionPerformed

        int index = tblAngazovanja.getSelectedRow();
        if (index != -1) {
            System.out.println(model.getAngazovanja().get(index).getNastavnik().getIme());
            System.out.println(nastavnik.getIme());
            if (model.getAngazovanja().get(index).getNastavnik().getIme().equals(nastavnik.getIme())) {
                model.getAngazovanja().remove(index);
                model.fireTableDataChanged();

            } else {
                JOptionPane.showMessageDialog(this, "Ne mozete menjati angazovanje od drugih nastavnika");

            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiAngActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoAngazovanje;
    private javax.swing.JButton btnObrisiAng;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPredmeti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblAngazovanja;
    // End of variables declaration//GEN-END:variables

    private void fillPredmetiCmb() {

        try {
            System.out.println("SALJEN NASTAVNIKA" + nastavnik);
            List<Predmet> predmeti = controller.getListaPredmetaByNastavnik(nastavnik);
           
            cmbPredmeti.setModel(new DefaultComboBoxModel(predmeti.toArray()));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void getPredmetCount() throws Exception {
        jTextArea1.append(nastavnik.getIme() + "\n" + nastavnik.getPrezime() + "\n");
        List<String> list = controller.getCountByTipAngazovanja(nastavnik);
        for (String s : list) {
            jTextArea1.append(s + "\n");
        }
    }
}
